### PR TITLE
Bug fix for deflating large files

### PR DESCRIPTION
**Pull request by dephraser**
Fix for Issue #15

### CODE REVIEW

**Comment by jlongridge** [comment]
Tested successfully against large (10Mb+) json files.

**Comment by aomega08** [comment]
Thank you for your contribution, I'll release the gem early next week with this fix :+1:

**Comment by jlongridge** [comment]
Thank you for merging this fix, please could I get an update on when a new gem version might be available?

**Comment by aomega08** [comment]
Sorry for the delay, for some reason most of my GH notifications end up in spam and I easily forget about the threads! Anyway, gem is now released, v0.3.1.

**Comment by jlongridge** [comment]
Thank you!

**Pull request merged**
