### PR TITLE
Dir algorithm

### LINKED ISSUE #12: Issues with the 'dir' Algorithm using bytes other than 16 on Ruby >= 2.4
With the updated openssl library within ruby 2.4 you get this error:  
key must be 16 bytes (ArgumentError)

I am ready with a quick rspec test case but it fails on anything > 2.4

### PR DESCRIPTION
**Pull request by rangeroob**
fixes #12

### CODE REVIEW

**Comment by aomega08** [comment]
Hey, thanks for the pull request. Unfortunately the travis build has failed, due to a gem install error... can you take care of that?

Also, did you investigate why the new openssl is asking for 16 bytes instead of 32? Was it truncating to 16 bytes anyway previously?

Thanks.

**Comment by rangeroob** [comment]
Hello I just fixed the pull request and to answer your questions yes it was previously working on ruby version 2.3.4 but I upgraded mid project and noticed it errors out on ruby version 2.4 even using your README's example

and I just found this on another projects github(https://github.com/attr-encrypted/encryptor/issues/26) issue which pointed me to the change in openssl(https://github.com/ruby/ruby/commit/ce635262f53b760284d56bb1027baebaaec175d1)

**Comment by lizGraham9CB** [comment]
Is this going to get merged? I'm still seeing the "key must be 16 bytes" error when encrypting with dir.

**Comment by rangeroob** [comment]
Sadly @lizGraham9CB  this pull request would not stop you from seeing that error message. This pull request that I did over a year ago basically changes the readme to use 16 bytes in the example and adds a test case to show that it errors out on anything later than ruby 2.4 with a byte size greater than 16. I believe it is not specific to this gem and has to do with OpenSSL. The links I provided in my previous message give so good examples to try to work around this issue.

**Pull request closed without merging**
